[main]
packages = [
    "app2unit",
    "bitwarden",
    "bluez",
    "brightnessctl",
    "chezmoi",
    "chromium",
    "docker",
    "docker-buildx",
    "docker-compose",
    "dolphin",
    "ffmpeg",
    "firefox",
    "fish",
    "foot",
    "git",
    "hypridle",
    "hyprland",
    "hyprpicker",
    "hyprpolkitagent",
    "imagemagick",
    "jq",
    "kitty",
    "less",
    "lf",
    "mako",
    "man-db",
    "man-pages",
    "neovim",
    "networkmanager",
    "noctalia-shell",
    "noto-fonts",
    "noto-fonts-cjk",
    "noto-fonts-emoji",
    "openssh",
    "openssl",
    "pavucontrol",
    "pipewire",
    "pipewire-audio",
    "pipewire-jack",
    "pipewire-pulse",
    "playerctl",
    "qbittorrent",
    "rsync",
    "steam",
    "ttf-noto-nerd",
    "ufw",
    "uwsm",
    "vesktop",
    "vicinae",
    "visual-studio-code-bin",
    "vlc",
    "vlc-plugins-all",
    "xdg-desktop-portal-hyprland",
]
