#    ❄️  ═══════════════════════════════════════════  ❄️
#
#              />  フ　　　🦊　konkon-dotfiles
#             |  _  _ l
#       🌸   /` ミ_xノ  こんこん。。。
#           /      |
#          /  ヽ   ノ         apps.conf
#         │   | | |
#
#                    one soul, many forms
#               shape-shifting configurations
#
#    ❄️  ═══════════════════════════════════════════  ❄️

$runApp = app2unit --
$terminal = $runApp $TERMINAL
$fallbackTerminal = foot
$terminalExec = $runApp $TERMINAL_EXEC
$fileManager = dolphin
$termFileManager = lf
$browser = $BROWSER
$fallbackBrowser = chromium
$menu = vicinae toggle
$editor = $EDITOR
$visualEditor = code