#    ❄️  ═══════════════════════════════════════════  ❄️
#
#              />  フ　　　🦊　konkon-dotfiles
#             |  _  _ l
#       🌸   /` ミ_xノ  こんこん。。。
#           /      |
#          /  ヽ   ノ         apps.conf
#         │   | | |
#
#                    one soul, many forms
#               shape-shifting configurations
#
#    ❄️  ═══════════════════════════════════════════  ❄️

$terminal = kitty
$fileManager = dolphin
$browser = firefox
$menu = vicinae
