#    ❄️  ═══════════════════════════════════════════  ❄️
#
#              />  フ　　　🦊　konkon-dotfiles
#             |  _  _ l
#       🌸   /` ミ_xノ  こんこん。。。
#           /      |
#          /  ヽ   ノ         apps.conf
#         │   | | |
#
#                    one soul, many forms
#               shape-shifting configurations
#
#    ❄️  ═══════════════════════════════════════════  ❄️

# Autostart necessary processes (like notifications daemons, status bars, etc.)

# Application launcher
exec-once = $runApp vicinae server

# Status bar
exec-once = $runApp qs -c noctalia-shell --no-duplicate

# Polkit agent
exec-once = systemctl --user start hyprpolkitagent

# Idle manager
exec-once = $runApp hypridle
